### ISSUE TITLE
slice indices must be integers or None or have an __index__ method**

### ISSUE THREAD

**Issue by fkolokathi** [spartakos87/greek_sites_crawler#3]
I run your program and I always take  the following error for every website:

<ipython-input-5-cfb454641153> in alfavita(html)
      1 def alfavita(html):
----> 2     topic = html.find("div",{"class":"field-item even"}).text
      3     title = html.title.text
      4     article = html.find("div",{"class":"field field-name-body field-type-text-with-summary field-label-hidden"}).text
      5     publish_time = html.find("span",{"class":"uk-text-muted uk-text-small"}).text.split('|')[0]

TypeError: **slice indices must be integers or None or have an __index__ method**

**Comment by spartakos87** [comment]
I just ckeck it looks fine to me , can you send me the url which try to crawl? 
PS Its run with python3

**Comment by fkolokathi** [comment]
Yes, you're right...It was my fault.I didn't follow your instructions...I did not call function get_html at the beginning but I passed the url to every function of each website directly..Congratulations for your program!!!!!!

**Comment by spartakos87** [comment]
Thnx a lot
