### ISSUE TITLE
Problem at published date

### ISSUE THREAD

**Issue by fkolokathi** [spartakos87/greek_sites_crawler#4]
Sorry again.When I ran your program for kathimerini I saw that for example for the link:

http://www.kathimerini.gr/915955/article/texnologia/diadiktyo/agaph-kai-orgh-gia-epityxhmena-tweets

it does not print the correct published date but it prints the today's date.I will check it for  all the remaining sites and if there's a problem I will post it here.

Moreover, you need to add greek_sites_crawler.py file
site['kathimerini']= kathimerini
site['lifo'] = lifo

**Comment by spartakos87** [comment]
Fix it
Thx for feedback
